version: '3.9'

services:
  dynamodb-local:
    container_name: dynamodb-local-kotlin
    image: amazon/dynamodb-local
    ports:
      - '8086:8000'
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
    volumes:
      - ./dynamodb_local:/data # ボリュームマウントができず、バイマウントにした。。。
    networks:
      - dynamoDB-kotlin
    restart: unless-stopped

  dynamodb-admin:
    container_name: dynamodb-admin-kotlin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    ports:
      - 8087:8001
    depends_on:
      - dynamodb-local
    networks:
      - dynamoDB-kotlin
networks:
  dynamoDB-kotlin:
    driver: bridge


